// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/foretify.proto
// </auto-generated>
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Morai.Protobuf.Foretify {
  /// <summary>
  /// The greeting service definition.
  /// </summary>
  public static partial class Foretify
  {
    static readonly string __ServiceName = "MoraiProtobufForetify.Foretify";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Morai.Protobuf.Foretify.init_req> __Marshaller_MoraiProtobufForetify_init_req = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Morai.Protobuf.Foretify.init_req.Parser));
    static readonly grpc::Marshaller<global::Morai.Protobuf.Foretify.init_resp> __Marshaller_MoraiProtobufForetify_init_resp = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Morai.Protobuf.Foretify.init_resp.Parser));
    static readonly grpc::Marshaller<global::Morai.Protobuf.Foretify.launch_simulator_req> __Marshaller_MoraiProtobufForetify_launch_simulator_req = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Morai.Protobuf.Foretify.launch_simulator_req.Parser));
    static readonly grpc::Marshaller<global::Morai.Protobuf.Foretify.launch_simulator_resp> __Marshaller_MoraiProtobufForetify_launch_simulator_resp = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Morai.Protobuf.Foretify.launch_simulator_resp.Parser));

    static readonly grpc::Method<global::Morai.Protobuf.Foretify.init_req, global::Morai.Protobuf.Foretify.init_resp> __Method_init = new grpc::Method<global::Morai.Protobuf.Foretify.init_req, global::Morai.Protobuf.Foretify.init_resp>(
        grpc::MethodType.Unary,
        __ServiceName,
        "init",
        __Marshaller_MoraiProtobufForetify_init_req,
        __Marshaller_MoraiProtobufForetify_init_resp);

    static readonly grpc::Method<global::Morai.Protobuf.Foretify.launch_simulator_req, global::Morai.Protobuf.Foretify.launch_simulator_resp> __Method_launch_simulator = new grpc::Method<global::Morai.Protobuf.Foretify.launch_simulator_req, global::Morai.Protobuf.Foretify.launch_simulator_resp>(
        grpc::MethodType.Unary,
        __ServiceName,
        "launch_simulator",
        __Marshaller_MoraiProtobufForetify_launch_simulator_req,
        __Marshaller_MoraiProtobufForetify_launch_simulator_resp);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Morai.Protobuf.Foretify.ForetifyReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Foretify</summary>
    [grpc::BindServiceMethod(typeof(Foretify), "BindService")]
    public abstract partial class ForetifyBase
    {
      /// <summary>
      /// SSP API
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Morai.Protobuf.Foretify.init_resp> init(global::Morai.Protobuf.Foretify.init_req request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Morai.Protobuf.Foretify.launch_simulator_resp> launch_simulator(global::Morai.Protobuf.Foretify.launch_simulator_req request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Foretify</summary>
    public partial class ForetifyClient : grpc::ClientBase<ForetifyClient>
    {
      /// <summary>Creates a new client for Foretify</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ForetifyClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Foretify that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ForetifyClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ForetifyClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ForetifyClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// SSP API
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Morai.Protobuf.Foretify.init_resp init(global::Morai.Protobuf.Foretify.init_req request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return init(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// SSP API
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Morai.Protobuf.Foretify.init_resp init(global::Morai.Protobuf.Foretify.init_req request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_init, null, options, request);
      }
      /// <summary>
      /// SSP API
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Morai.Protobuf.Foretify.init_resp> initAsync(global::Morai.Protobuf.Foretify.init_req request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return initAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// SSP API
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Morai.Protobuf.Foretify.init_resp> initAsync(global::Morai.Protobuf.Foretify.init_req request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_init, null, options, request);
      }
      public virtual global::Morai.Protobuf.Foretify.launch_simulator_resp launch_simulator(global::Morai.Protobuf.Foretify.launch_simulator_req request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return launch_simulator(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Morai.Protobuf.Foretify.launch_simulator_resp launch_simulator(global::Morai.Protobuf.Foretify.launch_simulator_req request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_launch_simulator, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Morai.Protobuf.Foretify.launch_simulator_resp> launch_simulatorAsync(global::Morai.Protobuf.Foretify.launch_simulator_req request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return launch_simulatorAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Morai.Protobuf.Foretify.launch_simulator_resp> launch_simulatorAsync(global::Morai.Protobuf.Foretify.launch_simulator_req request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_launch_simulator, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ForetifyClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ForetifyClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ForetifyBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_init, serviceImpl.init)
          .AddMethod(__Method_launch_simulator, serviceImpl.launch_simulator).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ForetifyBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_init, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Morai.Protobuf.Foretify.init_req, global::Morai.Protobuf.Foretify.init_resp>(serviceImpl.init));
      serviceBinder.AddMethod(__Method_launch_simulator, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Morai.Protobuf.Foretify.launch_simulator_req, global::Morai.Protobuf.Foretify.launch_simulator_resp>(serviceImpl.launch_simulator));
    }

  }
}
#endregion
